ALTER TABLE users ADD COLUMN status VARCHAR(30) DEFAULT 'REGISTRATION_PROGRESS';
ALTER TABLE users ADD COLUMN email_code VARCHAR(10);
ALTER TABLE users ADD COLUMN sms_code VARCHAR(10);
ALTER TABLE users ADD COLUMN email_verified BOOLEAN DEFAULT FALSE;
ALTER TABLE users ADD COLUMN phone_verified BOOLEAN DEFAULT FALSE;